//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgenstvoA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ИсторияКредитов
    {
        public int HistoryID { get; set; }
        public int LoanID { get; set; }
        public int EmployeeID { get; set; }
        public string Action { get; set; }
        public System.DateTime Timestamp { get; set; }
    
        public virtual Сотрудники Сотрудники { get; set; }
        public virtual Кредиты Кредиты { get; set; }
    }
}
